### ISSUE TITLE
Feature request - all()

### ISSUE THREAD

**Issue by Darrrren** [Anteris-Dev/autotask-client#15]
Any thoughts on implementing an `all()` method when querying the API Aidan instead of us having to specify a where clause with every call? For example:

`$results = $client->companies()->query()->all();` 

A native `get()` without a valid `where()` condition returns on empty CompanyCollection object for me. For example:

`$results = $client->companies()->query()->get();` 

I'm sure it would raise the question of implementing the `loop()` method again to get around the 500 limit documented in #7 and that would for sure satisfy this one as long as we had the option to drop the `where()` on every call. It's that mandatory `where()` condition that's driven me to document the request.

Just a quick thought as I'm having to think of creative ways to pull all records whilst having to use the where clause every time during testing.  Unless of course I've missed something somewhere :-)

So far so good, everything working as documented except a few tiny errors in this early version of the documentation which I'll collect together and raise an issue for in the coming days.

**Comment by aidan-casey** [comment]
I've been thinking about this as well. The required `where()` does not come from me, but rather the limitations of the Autotask API. Running a request on /query without an actual query returns the following error.

```json
{
    "errors": [
        "Value cannot be null.\r\nParameter name: filters"
    ]
}
```

Since where adds a filter it resolves that problem, necessitating that the where method is called. The only "workaround" I have found to this right now is to add `where('id', 'exist')` to the query, though this will fail on a couple of resources with the error "id cannot be queried." This is essentially the same issue referenced over at the [SOAP client](https://github.com/opendns/autotask-php/issues/164).

I am open to suggestions if you have them, but we may have to wait on Autotask to implement this.

Appreciate you collecting up those errors, I would love to get those fixed. In the early stages of our next version, unit tests have uncovered a couple big problems. Most of these are issues on Autotask's side, but we can implement some fixes for a few of them as well. Working on getting this released soon! (See also #12 )

**Comment by Darrrren** [comment]
> In the early stages of our next version, unit tests have uncovered a couple big problems. Most of these are issues on Autotask's side, but we can implement some fixes for a few of them as well. Working on getting this released soon! (See also #12 )

Yeah I saw these, are they affecting CRUD functionality at all in any of the entities?

Understand your point regarding the `all()` and the fact that its a function/symptom of the REST API, let's wait and see what Datto do about it in the future.  Thanks for the `where('id','exist')`, that's exactly what I've been doing.

**Comment by aidan-casey** [comment]
Primarily they are impacting the query (or read) actions against the API. This package expects entities to be returned as defined by `/entityInformation` and `/entityInformation/fields` (and they should be) but Autotask is inconsistent with the response. I have some quick fixes that will be ready for release soon. These will resolve those issues the best we can without Autotask fixing their end. They have been alerted to the issues.

You bet. I put a bug in their ear on that.

While I can understand the record limit, I would not limit developers to a query endpoint though. I would probably implement a GET request against the root endpoint (e.g. /companies) that displays companies in alphabetical form and can be paged through. I would probably embrace the [JSON:API spec](https://jsonapi.org/) while I'm at it.

A record limit of some kind is somewhat important. A looped request can be throttled, but a request that would result in potentially millions of records cannot be. I could see looping through the records when generating a report or something, but if dealing with user experience I would definitely slim that down and page it for them.

Here's to that coffee. ☕

**Comment by aidan-casey** [comment]
@Darrrren - I am going to close this issue. I am by no means opposed to the feature, but we need to see some cooperation with Autotask before we can implement. If we see that, we will revisit this.
