### ISSUE TITLE
Ledger information

### ISSUE THREAD

**Issue by Rodeveer** [Anteris-Dev/autotask-client#28]
During developing the new structure with this repository I came across something so called `generalLedgerAccount`;
I assume this is the ID of the specific ledger which is attached to the `BillingItem` > `BillingCode`;

Sadly I couldn't find the so called `service` within this repository yet. Am I blind or has this a different naming convention (that I don't know of). Or am I having amnesia and is this it? 🤔 

Thanks in advance for answering. 👍 

Regards,

**Comment by aidan-casey** [comment]
@Rodeveer - Are you asking about whether a service exists for General Ledger Accounts or Billing Items and Billing Codes? I was just a tad confused on that part.

We do have services for Billing Items and Billing Codes. You are correct that the `generalLedgerAccount` property on the BillingCode entity is the ID of the associated General Ledger Account in Autotask. Autotask has not yet exposed an endpoint for the General Ledger Accounts in their pre-release or production APIs, so that is not something we are able to support currently.

That said, as soon as they announce the development of such an endpoint, we will support it. 👍

**Comment by Rodeveer** [comment]
Just the Gerenal Ledger Account data. Which you can find under that! Sorry for the confusion.

That's great to hear. Thanks 👍

**Comment by Rodeveer** [comment]
I'd reopen the issue here again for the following reason:

I've checked my old code. Everything thats called `BillingCode` is actually equivalent of the `AllocationCode` in the Soap Response.
Weird enough it is exposed there (SOAP) trough a specific label from a `PickListValue`. I get the same value. I only miss the specific `Label` there. Maybe that does ring a bell?

Thanks again.

**Comment by aidan-casey** [comment]
For future reference, you can find this information by calling the getEntityFields() method on the BillingCodeService. From there you will need to find the GeneralLedgerAccount field and look at the `picklistValues` array under that field.

**Comment by Rodeveer** [comment]
I'm stupid. Found it the moment I did wrote the message. Thanks again.

**Comment by aidan-casey** [comment]
@Rodeveer - Not at all! I missed that at first too. 🙂
