### ISSUE TITLE
Not really a API isssue, but more a PHP question

### ISSUE THREAD

**Issue by Nomisdk86** [Anteris-Dev/autotask-client#30]
Hi

I am creating a module to create new contacts. 
But i am having trouble getting it to work if i like it to check if mobilephone or email is filled out.

My code:
`
# Create new contact
$contact = new Anteris\Autotask\API\Contacts\ContactEntity([
    'id' => 0, // Autotask requires that new entities have an ID of 0
    'companyID' => intval($Companyid),
    'firstName' => $Fornavn,
    'lastName' => $Efternavn,
    'isActive' => 1,
	'phone' => $Telefon,
]);
# Check if MobilPhone filled out
if (empty($MobilTelefon)) {
} else {
	$contact['mobilePhone'] = $MobilTelefon;
}
# Check if Email filled out
if (empty($Email)) {
} else {
	$contact['emailAddress'] = $Email;
}

# Create in Autotask
$client->contacts()->create( $contact );
`

I get the error:
Uncaught Error: Cannot use object of type Anteris\\Autotask\\API\\Contacts\\ContactEntity as array in 

If i remove the part with mobilephone and email it works fine.

**Comment by Nomisdk86** [comment]
Fixed: 
https://stackoverflow.com/questions/64848245/php-append-to-object

**Comment by aidan-casey** [comment]
Thanks for the issue and link to resolution @Nomisdk86! Just for anyone looking at this issue, the problem is that `Anteris\Autotask\API\Contacts\ContactEntity` is an Object which requires assignment via the arrow syntax (e.g. `$contact->mobilePhone`) vs. the array syntax listed above.

Good luck with your code @Nomisdk86! Be sure to let us know if you run into any other problems.
