### ISSUE TITLE
Need to add variable for purchaseOrderTemplateID to CompanyEntity.php

### ISSUE THREAD

**Issue by jeffreyabbott** [Anteris-Dev/autotask-client#35]
Recently the API client has begun to throw an exception because the purchaseOrderTemplateID was not found in the returned CompanyEntity.php.

I was able to patch it by adding the following line to the definition at line 60:

   public ?int $purchaseOrderTemplateID;

This seemed to have fixed the problem, but I am unsure if there is something else that needs to be done or in a different way.

Thank you.

**Comment by Darrrren** [comment]
Yep I can confirm this is an issue, thanks for the workaround, I'll put that into effect over here to.

**Comment by Darrrren** [comment]
Further to this issue I had to use Jeffery's fix in CountryEntity.php as well.

To aid the reader whilst waiting for a fix, insert the following line: 

`public ?int $purchaseOrderTemplateID;`

into here:

https://github.com/Anteris-Dev/autotask-client/blob/26cf69d61c59ca0a974882fb0c438737ad7955fe/src/API/Companies/CompanyEntity.php#L60

and here:

https://github.com/Anteris-Dev/autotask-client/blob/26cf69d61c59ca0a974882fb0c438737ad7955fe/src/API/Countries/CountryEntity.php#L21

**Comment by Rodeveer** [comment]
I'd like to have this also! Current client is having issue's with it. I'd rather NOT fork. (Which isnt even possible? 😋 )

**Comment by aidan-casey** [comment]
Hey guys, just want to make sure you know your voices are heard!

The root of these issues is found in the fact that Autotask is changing their response schematic faster than we can get the entities updated. We would consider this a bad practice on their part, since the versioning for the API has remained the same throughout. As a result of this, we have decided to focus our efforts on building an updated version of the client using either Active Record or array responses (let me know if you have a preference!) both of which would not be effected by those changes.

I will try to get an update out today to patch this current client along until we get that released.

**Comment by aidan-casey** [comment]
> I'd like to have this also! Current client is having issue's with it. I'd rather NOT fork. (Which isnt even possible? 😋 )

@Rodeveer - Forking is possible, but we would prefer not doing that as well. 👍🏼   The client is massive an heavy to maintain (something we are also looking to resolve).

**Comment by jeffreyabbott** [comment]
@aidan-casey  I don't really have a preference between Active Record or array responses. 

Active Record would be interesting from a software architecture angle, but would it add more complexity than an array?

And I am thankful you guys maintain this library. I concur with assessment of Autotasks schema changes without an API sub-version update.

Again, thank you.

**Comment by aidan-casey** [comment]
@jeffreyabbott - Thank you for the kind words and feedback! The initial investment in putting together an Active Record package might be a little more, but the code itself shouldn't be terribly complex. We would seek to model them off of Laravel models with the ability to save, update, delete, and query. The primary difference there would be that instead of a strongly typed schematic (as this package offers) it would be attributes created on the fly.

**Comment by Rodeveer** [comment]
@aidan-casey Thanks for the headsup! Sounds good. I much appreciate also the work youve guys have done for making this available! Maintaining a package is not an easy thing to do.

**Comment by Rodeveer** [comment]
Hey @aidan-casey !  It seems you didnt get a patch out last week. How is the progression going?
I've seen that someone actualy made a PR here: https://github.com/Anteris-Dev/autotask-client/pull/36;

I'd have to fork the repo for now since the client is missing over 2 weeks of data right now. (I only work 1 day per week for this client) and they told me they couldnt wait any longer. I'll revert back to your fix the moment the patch is in place!

**Comment by aidan-casey** [comment]
@Rodeveer - My bad. I do apologize!

We ran into some big problems with that patch due to entity information fields pulling in weird. For example, if you check the entityInformation/fields response for tickets, you will see the "rmmAlertId" field is returned as "rMMAlertId." This was causing a lot of parsing problems.

All that to say, keep an eye out for a patch today. After that we are looking to rapidly make progress on a more long-term solution. We are also in talks with Autotask about introducing a better versioning system and what that might look like.

**Comment by aidan-casey** [comment]
Feel free to take v0.5.0 for a spin. This should now be fixed.

**Comment by s7thamon** [comment]
Thank you for the updates! Active Record would be my vote, mostly due to working in Laravel.

**Comment by aidan-casey** [comment]
> Thank you for the updates! Active Record would be my vote, mostly due to working in Laravel.

Thanks for the feedback! That seems to be the consensus. We're working on something awesome for you guys!
