### ISSUE TITLE
Missing support for UDFs for several entities

### ISSUE THREAD

**Issue by optmsp** [Anteris-Dev/autotask-client#55]
Correct me if I'm mistaken, but most entities don't support UDFs in your library currently. I had to manually add support for UDFs in API/TicketService.php for example to get things working like they do with the Company entity.

It appears you are using a code generator to rebuild the project? I can't find what you are using in your repo. If you let me know what is needed, I can do the update to that and a PR to add support for all Autotask entities that support UDFs? I'd rather do that than have a fork on my side.

Let me know, thanks!

**Comment by aidan-casey** [comment]
Hey @optmsp!

Can you clear up for me what you had to manually add? There is a `userDefinedProperties` property on all entities that support UDFs (including tickets), but this should not require any editing to the service.

See this [older issue](https://github.com/Anteris-Dev/autotask-client/issues/34) for information on how to modify UDFs.

There is a code generator [here](https://github.com/anteris-dev/autotask-client-generator) though our current priorities are redoing the library entirely and in a more dynamic way so that changes to the Autotask API schema do not effect the client.

**Comment by optmsp** [comment]
I added this to TicketServixe so that I could fully work with UDFs, e.g., grabbing their ID to ensure I could properly track changes UDF name changes..


`    public function getEntityUserDefinedFields(): EntityUserDefinedFieldCollection
    {
        return EntityUserDefinedFieldCollection::fromResponse(
            $this->client->get("Tickets/entityInformation/userDefinedFields")
        );
    }
`


Without it, I'm not able to get this (that I can tell).

edit: I'm on mobile and can't tell if I'm wrecking that code insert or not..

**Comment by optmsp** [comment]
I had chance to sit down and see where/how I'm using this.

To grab the UDFs for Tickets, I do this:

```
        $result = $this->autotaskClient->userDefinedFieldDefinitions()->query()
            ->where('udfType', 'eq', $udfType)
            ->where('dataType', 'noteq', self::UDF_DATA_TYPE_PICKLIST_MULTI);
```

By grabbing this, we get an ID. 

We can then also call:

`$result = $this->autotaskClient->userDefinedFieldListItems()->query()->where('udfFieldId', 'eq', $someID);`

This returns the picklist items, along with their IDs. If we just use getEntityUserDefinedFields(), we don't get the ID on picklist items.  Without the ID, it's impossible to know if a new picklist choice is a new item or a renamed item.

Until I made the manual change to your library for Tickets, this only worked for Companies.

Is something broken on my side?

**Comment by aidan-casey** [comment]
@optmsp - What is the response from `getEntityInformation()` on the tickets service?
