### ISSUE TITLE
Query POST support in autotask-client

### ISSUE THREAD

**Issue by optmsp** [Anteris-Dev/autotask-client#77]
Unless there has been an update I missed, [github.com/Anteris-Dev/autotask-client](https://github.com/Anteris-Dev/autotask-client) does not support POST queries, correct? We are limited to GET queries (which have issues with string maxlen)?

If so, this is impacting me in re: to query performance for large queries.

I was going to tackle this personally but am swamped, so I'm going to bring in a contractor to write up the patch against autotask-client. I'm aware that you use a templating system to build our anteris-client. If we send the PR against this lib and the code can be scaled to all entities, can you backport that into your templating system so it is fully rolled out and supported in autotask-client?

Also, any specific rules of engagement you want the contractor to follow? My instructions were to adhere to your style and whatever methods you have and to not bring in new dependencies.

**Comment by aidan-casey** [comment]
@optmsp - I would highly recommend this be submitted to that template system, so that it could be applied to the entire package. This should not be too difficult to implement [here](https://github.com/Anteris-Dev/autotask-client-generator/blob/master/templates/Package/API/QueryBuilder.php.twig).

We have actions in place to automatically cleanup the code to a specific style, so no specific concerns there.

The biggest request I would have is that it be opt-in when the developer makes the call. This is due to caching concerns with the `get` and `paginate` methods.

**Comment by aidan-casey** [comment]
I should note, we are in the middle of a rewrite of this package [here](https://github.com/orgs/AutotaskPHP/projects/1). Because of this, I would not take the time to backport a PR to this specific repository, but I would accept one to the generator, which would update this repository.

**Comment by samdark** [comment]
https://github.com/Anteris-Dev/autotask-client-generator/pull/15

**Comment by aidan-casey** [comment]
@samdark and @w911 have added support for this in the latest release.
